set(CTEST_PROJECT_NAME "RGG-Nuclear-GUI")
set(CTEST_NIGHTLY_START_TIME "21:00:00 EDT")

set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "open.cdash.org")
set(CTEST_DROP_LOCATION "/CDash/submit.php?project=RGG")
set(CTEST_DROP_SITE_CDASH TRUE)
